[2024-09-01T15:14:04.149+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-01T15:14:04.195+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.evaluate_model manual__2024-09-01T15:08:03.776807+00:00 [queued]>
[2024-09-01T15:14:04.216+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.evaluate_model manual__2024-09-01T15:08:03.776807+00:00 [queued]>
[2024-09-01T15:14:04.219+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-09-01T15:14:04.273+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): evaluate_model> on 2024-09-01 15:08:03.776807+00:00
[2024-09-01T15:14:04.315+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=701) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T15:14:04.325+0000] {standard_task_runner.py:72} INFO - Started process 710 to run task
[2024-09-01T15:14:04.335+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'evaluate_model', 'manual__2024-09-01T15:08:03.776807+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpfpt3pgws']
[2024-09-01T15:14:04.338+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask evaluate_model
[2024-09-01T15:14:04.469+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline.evaluate_model manual__2024-09-01T15:08:03.776807+00:00 [running]> on host e851988aa96f
[2024-09-01T15:14:07.367+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='evaluate_model' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T15:08:03.776807+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T15:08:03.776807+00:00'
[2024-09-01T15:14:07.370+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-01T15:14:07.371+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-01T15:14:07.373+0000] {logging_mixin.py:190} INFO - Current task name:evaluate_model state:running start_date:2024-09-01 15:14:04.196522+00:00
[2024-09-01T15:14:07.375+0000] {logging_mixin.py:190} INFO - Dag name:ml_pipeline and current dag run status:running
[2024-09-01T15:14:07.376+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-01T15:14:07.379+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 48, in evaluate_model
    with open(model_path, 'rb') as model_file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'None'
[2024-09-01T15:14:07.408+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-01T15:14:07.410+0000] {logging_mixin.py:190} INFO - Task start:2024-09-01 15:14:04.196522+00:00 end:2024-09-01 15:14:07.407929+00:00 duration:3.211407
[2024-09-01T15:14:07.411+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): evaluate_model> dag:<DAG: ml_pipeline> dagrun:<DagRun ml_pipeline @ 2024-09-01 15:08:03.776807+00:00: manual__2024-09-01T15:08:03.776807+00:00, state:running, queued_at: 2024-09-01 15:08:03.810719+00:00. externally triggered: True>
[2024-09-01T15:14:07.412+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'None'
[2024-09-01T15:14:07.413+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=evaluate_model, run_id=manual__2024-09-01T15:08:03.776807+00:00, execution_date=20240901T150803, start_date=20240901T151404, end_date=20240901T151407
[2024-09-01T15:14:07.443+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-01T15:14:07.445+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task evaluate_model ([Errno 2] No such file or directory: 'None'; 710)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 48, in evaluate_model
    with open(model_path, 'rb') as model_file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'None'
[2024-09-01T15:14:07.538+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-01T15:14:07.594+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T15:14:07.606+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
